name: 'Create release'
description: 'Create releases for tags'

runs:
  using: "composite"
  steps:
    - name: Set Tag Name
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        TAG_NAME=$(echo "${GITHUB_REF#refs/tags/}" | sed 's|/|_|g')
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

    - name: Set Final Archive Name
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        FINAL_NAME="${ZIP_NAME}_${TAG_NAME}_${TIMESTAMP}"
        echo "FINAL_ARCHIVE_NAME=${FINAL_NAME}" >> $GITHUB_ENV
        mv "${ZIP_NAME}" "${FINAL_NAME}"
        echo "Folder renamed to ${FINAL_NAME}"
        ls -la "${FINAL_NAME}"

    - name: Archive Release
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        zip -r "${FINAL_ARCHIVE_NAME}.zip" "${FINAL_ARCHIVE_NAME}"
        echo "ZIP created: ${FINAL_ARCHIVE_NAME}.zip"
        ls -lh "${FINAL_ARCHIVE_NAME}.zip"

    - name: Generate artifact attestation
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: ${{ env.FINAL_ARCHIVE_NAME }}.zip

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.FINAL_ARCHIVE_NAME }}.zip
